### ISSUE TITLE
What was your motivation to create this package?

### ISSUE THREAD

**Issue by meehow** [kaitoy/disturb-me#1]
I think that you should describe in README file:
- What was your motivation to create this package?
- How people can use it and benefit from it?

It is little bit weird, but also quite interesting.
At first I thought that it's very useless and created only for fun, but I think that it can be used for some concentration training.

**Comment by kaitoy** [comment]
I just wanted to create a useless package...
Many very useful packages are already created but no package just for fun as far as I searched.
I wanted to release such package and see reactions. (Originally I wanted to move Pacman who eats text in atom window, but I gave up it due to copyright concerns.)
I have no idea for benefit people can get form disturb-me.
